make:
	g++-4.8 -w -O2 make_cdf.cc -o make_cdf -lm 
	g++-4.8 -w -O2 make_fairness_index.cc -o make_fairness_index  -lm
	g++-4.8 -w -O2 make_plr.cc -o make_plr  -lm
	g++-4.8 -w -O2 make_cell_spectral_efficiency.cc -o make_cell_spectral_efficiency  -lm
	g++-4.8 -w -O2 make_goodput.cc -o make_goodput -lm 
	g++-4.8 -w -O2 make_sum.cc -o make_sum -lm 
	g++-4.8 -w -O2 make_avg.cc -o make_avg -lm 
	g++-4.8 -w -O2 make_gput.cc -o make_gput -lm 
clean:
	rm -f make_cdf make_gput make_avg make_sum make_fairness_index make_plr make_cell_spectral_efficiency make_goodput


